//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class devTestUserResult
    {
        public string id { get; set; }
        public string userId { get; set; }
        [Display(Name = "Test Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime dateTaken { get; set; }
        [Display(Name = "Test Result")]
        public int testResultNumerator { get; set; }
        public int testResultDenominator { get; set; }

        public string testResult
        {
            get
            {
                return testResultNumerator.ToString("00") + "/" + testResultDenominator.ToString("00");
            }
        }
    
        public virtual devTestUser devTestUser { get; set; }
    }
}
